export const types = {
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',

	PROVIDER_INFO: 'PROVIDER_INFO',
	GET_ASSETS: 'GET_ASSETS',
	RESET_ASSETS: 'RESET_ASSETS',

	GET_CUSTOMERS: 'GET_CUSTOMERS',
	RESET_CUSTOMERS: 'RESET_CUSTOMERS',
	ADD_CUSTOMER: 'ADD_CUSTOMER',
	EDIT_CUSTOMER: 'EDIT_CUSTOMER',
	DELETE_CUSTOMER: 'DELETE_CUSTOMER',

	GET_ROOMS: 'GET_ROOMS',
	RESET_ROOMS: 'RESET_ROOMS',
	ADD_ROOM: 'ADD_ROOM',
	EDIT_ROOM: 'EDIT_ROOM',
	DELETE_ROOM: 'DELETE_ROOM',
	
	GET_CONCERTS: 'GET_CONCERTS',
	RESET_CONCERTS: 'RESET_CONCERTS',
	ADD_CONCERT: 'ADD_CONCERT',
	EDIT_CONCERT: 'EDIT_CONCERT',
	DELETE_CONCERT: 'DELETE_CONCERT'
};
